name: "Package-Setup"
inputs:
  python-version:
    description: "Python version"
    required: true

  virtualenvs_create:
    descreption: ""
    required: false
    default: true

  virtualenvs_in_project:
    description: ""
    required: false
    default: true

runs:
  env:
    VIRTUALENVS_CREATE: ${{ input.virtualenvs_create}}
    VIRTUALENVS_IN_PROJECT: ${{ input.virtualenvs_in_project}}
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: "Cache-Packages"
      uses: actions/cache@v2
      id: cache-packages
      with:
        path: .venv
        key: poetry-local-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/main.yml') }}

    - name: Install dependencies
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: poetry install
      shell: bash
