name: "Package-Setup"
inputs:
  python-version:
    description: "Python version"
    required: false

  virtualenvs_create:
    description: ""
    required: true
    default: true

  virtualenvs_in_project:
    description: ""
    required: true
    default: true

runs:
  using: "composite"
  steps:
    - name:
      run: echo $VIRTUALENVS_CREATE
      shell: bash

    - env:
      VIRTUALENVS_CREATE: ${{ inputs.virtualenvs_create}}
      VIRTUALENVS_IN_PROJECT: ${{ inputs.virtualenvs_in_project}}

    - name: "Checkout"
      uses: actions/checkout@v2

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: "Cache-Packages"
      uses: actions/cache@v2
      id: cache-packages
      with:
        path: .venv
        key: poetry-local-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/main.yml') }}

    - name: Install dependencies
      if: steps.cache-packages.outputs.cache-hit != 'true'
      run: poetry install
      shell: bash
