name: "Poetry-Setup"
inputs:
  python-version:
    description: "Python version"
    required: true
  poetry-version:
    description: "Poetry version"
    required: true
  poetry-dynamic-versioning-version:
    description: "Poetry dynamic version"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: "Cache-Poetry"
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: ${{ runner.os }}-poetry-${{ inputs.poetry-version }}-${{ inputs.poetry-dynamic-version }}-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-${{ inputs.poetry-version }}-${{ inputs.poetry-dynamic-version }}-${{ inputs.python-version }}-

    - name: "Install-Poetry"
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry self add poetry-dynamic-versioning[plugin]@${{ inputs.poetry-dynamic-versioning-version }}
