name: Publish python distribution to testPyPI

on:
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m pip install poetry-dynamic-versioning

      - name: Poetry config set
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Install poetry dependencies
        run: |
          poetry lock
          poetry install --no-ansi

      - name: Poetry publish
        run: |
          poetry publish --build -r testpypi
