name: Python-Format-Lint-Test-Publish

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://test.pypi.org/p/deize-method
    permissions:
      id-token: write
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          source $HOME/.poetry/env
          poetry install self add "poetry-dynamic-versioning[plugin]"

      - name: Install dependencies
        run: |
          poetry lock
          poetry install --no-ansi

  format-lint-commit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run format
        run: |
          poetry run black tests src
          poetry run isort tests src

      - name: Run lint
        run: |
          poetry run flake8 tests src
          poetry run mypy tests src

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Code Formatter Change

  Publish:
    needs: format-lint-commit
    runs-on: ubuntu-latest
    steps:
      - name: Poetry build
        run: |
          poetry build

      - name: Publish package distributions to testPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/
